HNM_UNIFIED_CLASS_MAPPING = {
    'Vest top': 'Top',
    'Bra': 'Underwear',
    'Underwear Tights': 'Underwear',
    'Socks': 'Unclassified',
    'Leggings/Tights': 'Underwear',
    'Sweater': 'Shirt',
    'Top': 'Top',
    'Trousers': 'Pants',
    'Hair clip': 'Accessories',
    'Umbrella': 'Unclassified',
    'Pyjama jumpsuit/playsuit': 'Unclassified',
    'Bodysuit': 'Body',
    'Hair string': 'Accessories',
    'Unknown': 'None',
    'Hoodie': 'Hoodie',
    'Sleep Bag': 'Unclassified',
    'Hair/alice band': 'Accessories',
    'Belt': 'Accessories',
    'Boots': 'Shoes',
    'Bikini top': 'Unclassified',
    'Swimwear bottom': 'Unclassified',
    'Underwear bottom': 'Unclassified',
    'Swimsuit': 'Unclassified',
    'Skirt': 'Skirt',
    'T-shirt': 'T-Shirt',
    'Dress': 'Dress',
    'Hat/beanie': 'Hat',
    'Kids Underwear top': 'Undershirt',
    'Shorts': 'Shorts',
    'Shirt': 'Shirt',
    'Cap/peaked': 'Hat',
    'Pyjama set': 'Unclassified',
    'Sneakers': 'Shoes',
    'Sunglasses': 'Accessories',
    'Cardigan': 'Outwear',
    'Gloves': 'Accessories',
    'Earring': 'Accessories',
    'Bag': 'Bag',
    'Blazer': 'Blazer',
    'Other shoe': 'Shoes',
    'Jumpsuit/Playsuit': 'Unclassified',
    'Sandals': 'Shoes',
    'Jacket': 'Outwear',
    'Costumes': 'Unclassified',
    'Robe': 'Unclassified',
    'Scarf': 'Accessories',
    'Coat': 'Longsleeve',
    'Other accessories': 'Accessories',
    'Polo shirt': 'Polo',
    'Slippers': 'Shoes',
    'Night gown': 'Unclassified',
    'Alice band': 'Accessories',
    'Straw hat': 'Hat',
    'Hat/brim': 'Hat',
    'Tailored Waistcoat': 'Outwear',
    'Necklace': 'Accessories',
    'Ballerinas': 'Unclassified',
    'Tie': 'Accessories',
    'Pyjama bottom': 'Unclassified',
    'Felt hat': 'Hat',
    'Bracelet': 'Accessories',
    'Blouse': 'Blouse',
    'Outdoor overall': 'Unclassified',
    'Watch': 'Accessories',
    'Underwear body': 'Body',
    'Beanie': 'Hat',
    'Giftbox': 'None',
    'Sleeping sack': 'Unclassified',
    'Dungarees': 'Pants',
    'Outdoor trousers': 'Pants',
    'Wallet': 'Accessories',
    'Swimwear set': 'Unclassified',
    'Swimwear top': 'Unclassified',
    'Flat shoe': 'Shoes',
    'Garment Set': 'Unclassified',
    'Ring': 'Accessories',
    'Waterbottle': 'None',
    'Wedge': 'None',
    'Long John': 'Underwear',
    'Outdoor Waistcoat': 'Outwear',
    'Pumps': 'Shoes',
    'Flip flop': 'Shoes',
    'Braces': 'Accessories',
    'Bootie': 'Unclassified',
    'Fine cosmetics': 'None',
    'Heeled sandals': 'Shoes',
    'Nipple covers': 'None',
    'Chem. cosmetics': 'None',
    'Soft Toys': 'None',
    'Hair ties': 'Accessories',
    'Underwear corset': 'Underwear',
    'Bra extender': 'Accessories',
    'Underdress': 'Underwear',
    'Underwear set': 'Underwear',
    'Sarong': 'Outwear',
    'Leg warmers': 'Unclassified',
    'Blanket': 'Unclassified',
    'Hairband': 'Accessories',
    'Tote bag': 'Bag',
    'Weekend/Gym bag': 'Bag',
    'Cushion': 'Unclassified',
    'Backpack': 'Bag',
    'Earrings': 'Accessories',
    'Bucket hat': 'Hat',
    'Flat shoes': 'Shoes',
    'Heels': 'Shoes',
    'Cap': 'Hat',
    'Shoulder bag': 'Bag',
    'Side table': 'None',
    'Accessories set': 'Accessories',
    'Headband': 'Accessories',
    'Baby Bib': 'Accessories',
    'Keychain': 'Accessories',
    'Dog Wear': 'Unclassified',
    'Washing bag': 'Unclassified',
    'Sewing kit': 'None',
    'Cross-body bag': 'Bag',
    'Moccasins': 'Shoes',
    'Towel': 'Accessories',
    'Wood balls': 'None',
    'Zipper head': 'Accessories',
    'Mobile case': 'None',
    'Pre-walkers': 'Shoes',
    'Toy': 'None',
    'Marker pen': 'None',
    'Bumbag': 'Bag',
    'Dog wear': 'Unclassified',
    'Eyeglasses': 'Accessories',
    'Wireless earphone case': 'Accessories',
    'Stain remover spray': 'None',
    'Clothing mist': 'None'
}